### ISSUE TITLE
Conda Package

### ISSUE THREAD

**Issue by OSUmageed** [lanl/ExactPack#3]
Hey, there's nothing in your conda package anymore so the README instructions don't work.  I had been using exactpack, but then I re-installed conda so the install didn't work.  I fixed it by cloning the repo and installing it while in my preferred conda environment.  But you should update your public package release.

Also do you have any publication or doi associated with this that I could cite in a paper?  Thanks.

**Comment by woodscn** [comment]
We removed the conda package, related to Issue #2. The documentation will be fixed very soon.

There is no ExactPack paper available yet, though there are a number of documents related to it available through osti.gov. Perhaps one of those will suit your needs?

Glad to hear that you're using the software, and sorry about the trouble this has caused!

**Comment by swdoebling-lanl** [comment]
Fixed in release 1.5.2
