### ISSUE TITLE
gfortran installation error

### ISSUE THREAD

**Issue by MMAN114** [lanl/ExactPack#4]
Hello, 

Please help me to fix this problem. While running gfortran on my Mac Catalina OS. It gives me the error: 

Library not loaded: /usr/local/gfortran/lib/libgfortran.3.dylib 

I installed gcc with brew command. And many times I reinstalled it <brew reinstall gcc>, but the same result. 

Any help would be much appreciated. 
Thanks.

**Comment by woodscn** [comment]
Unfortunately, most of the team is away for Christmas, so we can’t test your issue right away. I suspect a version mismatch with python libraries. How did you install python/numpy?

**Comment by MMAN114** [comment]
Thank you for your reply. I see, no problem to wait. I installed python via anaconda graphical installer. 

Thanks.

**Comment by woodscn** [comment]
What are the results of the commands:

> gfortran —version

> python —version

**Comment by MMAN114** [comment]
gfortran --version 
                      GNU Fortran (GCC) 8.2.0
python --version
                      Python 3.7.4

**Comment by woodscn** [comment]
Well, for starters, we still haven’t released support for python 3. That might be part of the problem.

**Comment by MMAN114** [comment]
Ok. Thanks .

**Comment by woodscn** [comment]
Did the version conflict resolve your problem?

**Comment by MMAN114** [comment]
No, it still continues.  Thanks.

**Comment by woodscn** [comment]
I attempted this on a Mac with Anaconda 3 and the default homebrew gcc. I observed testing errors (to be expected due to lack of Python3 support), but could not reproduce the issue @MMAN114 observed.
